# PwingNpc Configuration

# Default settings for new NPCs
defaults:
  spawn-on-load: true
  look-close:
    enabled: true
    range: 5.0
  
# General plugin settings
settings:
  max-view-distance: 48
  save-interval: 300 # In seconds, 300 = 5 minutes
  
# Debug settings
debug:
  enabled: false
  log-packets: false
